[package]
name = "pac2"
version = "0.1.0"
authors = ["Thoren Paulson <thoren.paulson@gmail.com>"]
edition = "2018"

[dependencies]
protobuf = "2.10.1"

[build-dependencies]
protobuf-codegen-pure = "2.10.1"
